### ISSUE TITLE
AW

### ISSUE THREAD

**Issue by Gustavissimo** [lguizi/Artwalk-Bot#1]
Olá, tenho interesse no Bot Artwalk, podemos conversar mais sobre isso? Posso auxiliar nos testes caso necessário. 
Tenho algumas informações provavelmente úteis...
Analiso o mercado de sneakers há um bom tempo.

**Comment by lguizi** [comment]
Olá bom dia,
o projeto está parado por enquanto, estou usando o que tenho aqui somente para uso próprio.
Talvez eu venha distribuir alguma ferramenta para facilitar vocês nos drops futuramente, mas por enquanto não tenho previsão. Obrigado!
